\connect to keycloakdb

GRANT USAGE, CREATE ON SCHEMA public TO kc_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kc_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO kc_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kc_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO kc_admin;

\connect to productdb

GRANT ALL PRIVILEGES  ON DATABASE productdb TO jzargo;

GRANT USAGE, CREATE ON SCHEMA public TO jzargo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jzargo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO jzargo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jzargo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO jzargo;
