syntax="proto3";

option java_package = "com.jzargo.protobuf";
option java_multiple_files = true;

service MediaService{
  // Server-streaming
  rpc getMediaContent(MediaContentURI) returns (stream MediaFile) {}

  // Unary
  rpc existsByUri(VersionedURI) returns (DoesMediaContentExist) {}

  // Client-streaming
  // change avatar is a remote method that replaces current file by the same uri
  rpc changeMediaFile(stream ChangeMediaFile) returns (VersionedURI) {}
  rpc addMediaFile(stream MediaFile) returns (VersionedURI) {}
}

message MediaFile{
  bytes contentChunk = 1;
}

message MediaFileMetadata{
  string fileUri = 1;
  ContentType contentType = 2;
}

message ChangeMediaFileMetadata{
  string previousVersion = 1;
}

message ChangeMediaFile {
  bytes contentChunk = 1;
}



enum ContentType {
  JPEG = 0;
  PNG  = 1;
  MP4  = 2;
  WEBP = 3;
  WEBM = 4;
}

message MediaContentURI {
  string mediaURI = 1;
}

message DoesMediaContentExist{
  bool isExists= 1;
  string uri = 2;
  string version = 3;
}

message VersionedURI {
  string uri = 1;
  string version = 2;
}