package com.jzargo.productservice.entity;


public enum SagaStep {
    PENDING_INVENTORY, PENDING_PRICE, PENDING_ASSETS,
    COMPENSATE_INVENTORY, COMPENSATE_PRICE, COMPENSATE_ASSETS, COMPENSATE_PRODUCT,
    FINISHED, FAILED
}
