spring:

  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jzargo
    password:  root123
    url: jdbc:postgresql://localhost:5432/productdb
