server:
  port: 8080
spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: devconfig
  kafka:
    admin:
      close-timeout: 10s