spring:
  application:
    name: media-service
  profiles:
    active: devconfig
  config:
    import: configserver:http://localhost:8888
  grpc:
    server:
      port: 8081
  cloud:
    aws:
      region:
        static: kz-central-1